;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	fc-eval-and-replace
	indent-for-tab-command
	kill-region
	python-backspace
	python-electric-colon
	python-find-imports
	))

(setq mc/cmds-to-run-once
      '(
	ido-write-file
	increment-number-at-point
	python-beginning-of-block
	))
